In [1]:
import numpy as np

## Reshape
Reshaping means changing the shape of an array.

In [3]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Unknown Dimension
> Pass -1 as the value, and NumPy will calculate this number for you.
Pass -1 as the value, and NumPy will calculate this number for you.
Note: We can not pass -1 to more than one dimension.

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr = newarr.reshape(-1, ) # Flattening the arrays
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
