In [2]:
import numpy as np

## Reshape
Reshaping means changing the shape of an array.

In [3]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Unknown Dimension
> Pass -1 as the value, and NumPy will calculate this number for you.
Pass -1 as the value, and NumPy will calculate this number for you.
Note: We can not pass -1 to more than one dimension.

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr = newarr.reshape(-1, ) # Flattening the arrays
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


##  Pick up values

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print('Pick up the third row of data', newarr[2,:] - newarr[1, :])
print('Pick up the third row of data', newarr[:,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Pick up the third row of data [3 3 3]
Pick up the third row of data [ 3  6  9 12]


In [12]:
# calculate the distance of two point

dis = np.sqrt(sum((newarr[2,:] - newarr[1, :]) ** 2))
print(dis)


5.196152422706632


In [22]:
mean = np.mean(newarr, axis=0)
print(mean)

[5.5 6.5 7.5]
