In [58]:
import numpy as np

## Reshape
Reshaping means changing the shape of an array.

In [3]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Unknown Dimension
> Pass -1 as the value, and NumPy will calculate this number for you.
Pass -1 as the value, and NumPy will calculate this number for you.
Note: We can not pass -1 to more than one dimension.

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr = newarr.reshape(-1, ) # Flattening the arrays
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


##  Pick up values

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print('Pick up the third row of data', newarr[2,:] - newarr[1, :])
print('Pick up the third row of data', newarr[:,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Pick up the third row of data [3 3 3]
Pick up the third row of data [ 3  6  9 12]


In [66]:
col_1 = newarr[:, 0]
print([col_1 == 1])

print('Pick up the third row of data', newarr[:, 2][col_1 == 1])
newarr[:, 2]

[array([ True, False, False, False])]
Pick up the third row of data [3]


array([ 3,  6,  9, 12])

In [12]:
# calculate the distance of two point

dis = np.sqrt(sum((newarr[2,:] - newarr[1, :]) ** 2))
print(dis)


5.196152422706632


In [22]:
mean = np.mean(newarr, axis=0)
print(mean)

[5.5 6.5 7.5]


In [24]:
## Random

rand = np.random.permutation(10)
print(rand)

[2 5 7 3 4 6 9 0 1 8]


In [39]:
k = 3
m = 100
idx = np.zeros(m, dtype=int)
for i in range(m):
    idx[i] = np.random.permutation(k)[0]

centroids = np.random.rand(4,3)
print(idx)
print(centroids)

print(idx.shape)
print(centroids.shape)

X_recovered = centroids[idx, :]
print(X_recovered)

[1 2 2 0 2 1 1 0 2 2 0 0 0 0 2 1 1 1 0 2 1 0 0 2 1 0 1 1 2 2 2 2 0 2 1 2 0
 1 0 2 0 0 1 1 0 1 1 0 0 1 0 2 2 0 2 0 2 0 0 1 2 2 1 2 0 0 0 0 2 1 1 2 2 2
 0 0 1 2 1 0 2 2 0 0 0 1 2 1 0 0 1 0 0 2 0 1 1 2 0 1]
[[0.05900526 0.57605746 0.28791747]
 [0.52527246 0.13058391 0.63370729]
 [0.25040951 0.85925248 0.12286498]
 [0.49723665 0.25281358 0.17687664]]
(100,)
(4, 3)
[[0.52527246 0.13058391 0.63370729]
 [0.25040951 0.85925248 0.12286498]
 [0.25040951 0.85925248 0.12286498]
 [0.05900526 0.57605746 0.28791747]
 [0.25040951 0.85925248 0.12286498]
 [0.52527246 0.13058391 0.63370729]
 [0.52527246 0.13058391 0.63370729]
 [0.05900526 0.57605746 0.28791747]
 [0.25040951 0.85925248 0.12286498]
 [0.25040951 0.85925248 0.12286498]
 [0.05900526 0.57605746 0.28791747]
 [0.05900526 0.57605746 0.28791747]
 [0.05900526 0.57605746 0.28791747]
 [0.05900526 0.57605746 0.28791747]
 [0.25040951 0.85925248 0.12286498]
 [0.52527246 0.13058391 0.63370729]
 [0.52527246 0.13058391 0.63370729]
 [0.52527246 0.13058391 0

### Random

In [56]:
from numpy.random import Generator, PCG64

rng = np.random.default_rng(7)
print(rng.permutation(100))

[88 42 26 50 54 70  4 53 24 32 19 10  1  2 94 91 68 23 46 40 16 93 48 73
 80 36 28 12  7 96 35 61 44 17  6 56 45 97 29 37 77 58  0 82 74 78 79 20
 39 98 75 67 57 51 64 14 92  8 49 22 85 47 65 90 83 62 99 89 27 63 76  9
  3 55 59 84 86 13 81 30 18 31 34  5 72 71 33 15 38 87 52 25 69 43 66 95
 60 21 41 11]


In [61]:
# a = 0.940 - (8 /14) * (-2/8 * np.log2(2/8) -6/8 * np.log2(6/8)) - (6/14)(-3/6 * np.log2(3/6) -3/6 * np.log2(3/6))
a= 0.940
b = (8/14) * (-2/8 * np.log2(2/8) -6/8 * np.log2(6/8))
c = (6/14)* (-3/6 * np.log2(3/6) -3/6 * np.log2(3/6))

print(f'{a} - {b} - {c} = {a-b-c}')

0.94 - 0.46358749969093305 - 0.42857142857142855 = 0.04784107173763835
